### ISSUE TITLE
Does this project use WebSharper UI?

### ISSUE THREAD

**Issue by codec-abc** [fsbolero/TodoMVC#2]
Hi,

Does this project use WebSharper UI? 

I think not but it says this on the page title as [seen here](https://github.com/fsbolero/TodoMVC/blob/6b21638a02b2f5f625f62039e55d14477148e993/src/Bolero.TodoMVC.Client/wwwroot/index.html#L4).

Is this a typo?

**Comment by granicz** [comment]
Good catch, this sample was borrowed from WebSharper indeed, but it does not require WebSharper. One of the original design goals of Bolero is to enable porting WebSharper applications to WebAssembly with minimal effort, hence the nearly identical copy of the original sample here. [This blog post](https://forums.websharper.com/blog/86183) explains more of the idea.

**Comment by granicz** [comment]
Corrected app title in d6d65cb794e07c888185a82f8d9449d721579c73
